# Generated by Django 5.2 on 2025-04-29 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Original filename or folder name', max_length=255)),
                ('s3_key', models.CharField(blank=True, help_text="S3 key (e.g., 'uuid/uuid-filename.ext'). Null for folders.", max_length=512, null=True, unique=True)),
                ('entry_type', models.CharField(choices=[('file', 'File'), ('folder', 'Folder')], db_index=True, max_length=10)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent folder entry. Null for root level items.', limit_choices_to={'entry_type': 'folder'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='storage.entry')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
                'ordering': ['name'],
            },
        ),
    ]
