# Generated by Django 5.2 on 2025-04-29 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['parent'], name='storage_ent_parent__ce772e_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['user'], name='storage_ent_user_id_50c64a_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['entry_type'], name='storage_ent_entry_t_74f8c6_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['s3_key'], name='storage_ent_s3_key_4f2e3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('parent', 'name', 'user')},
        ),
    ]
