# Generated by Django 5.2 on 2025-05-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='s3_key',
            field=models.TextField(blank=True, help_text="S3 key (e.g., 'uuid/uuid-filename.ext'). Null for folders.", null=True, unique=True),
        ),
    ]
