# Generated by Django 5.2 on 2025-05-01 01:02

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', apps.users.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, help_text="User's address information.", verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cognito_sub',
            field=models.CharField(blank=True, db_index=True, help_text='Unique identifier from AWS Cognito.', max_length=255, null=True, unique=True, verbose_name='Cognito Subject ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Required. Used for login and communication.', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False, help_text="Designates whether the user's email is verified in Cognito.", verbose_name='email verified'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, help_text="User's full name (potentially synced from Cognito 'name' claim).", max_length=255, verbose_name='full name'),
        ),
    ]
